### ISSUE TITLE
Docker: cannot run

### ISSUE THREAD

**Issue by tpnonthealps** [spacemeowx2/s3si.ts#15] opened 2022-11-05 12:42 UTC
![螢幕截圖 2022-11-04 00 07 16](https://user-images.githubusercontent.com/7851076/200120154-1fd112f6-cafc-4262-b397-c98886348e0e.png)

**Comment by laxect** [comment] 2022-11-05 13:26
Context: the Dockerfile is [here](https://paste.sr.ht/~fubuki/77190c2fc9177877654170c5a220980cd3f02e0b)

**Comment by spacemeowx2** [comment] 2022-11-05 17:17
Hi, what's the docker command do you run? Maybe mount the directory of `profile.json` make it work

**Comment by tpnonthealps** [comment] 2022-11-05 18:17
`docker run -v $PWD/profile.json:/app/profile.json  -d s3si`

**Comment by spacemeowx2** [comment] 2022-11-10 13:30
I can't reproduce (on Windows, Mac, Docker Desk). Maybe there is a program that happens to be occupying this file. Make sure that `profile.json` is mounted in read-write state at the time of execution.

Close this issue for now. Feel free to open it again if you have any additional information

**Closed by spacemeowx2** 2022-11-10 13:30 UTC
