### ISSUE TITLE
[error] "Membership required error."

### ISSUE THREAD

**Issue by Peterpig** [spacemeowx2/s3si.ts#20] opened 2022-11-16 09:08 UTC
![image](https://user-images.githubusercontent.com/7956973/202137517-d6801c79-f247-4b02-aa67-720149256437.png)

anyone konw how to fix？
thanks

**Comment by spacemeowx2** [comment] 2022-11-16 09:19
This error is from Nintendo, meaning that the account you are logged into is not a Nintendo Switch Online member.

This is usually caused by you logging into an account that is not the one you expected.

Please check that the account you are logged into is the same as the account you have on your switch.

This issue should not be related to the project, close it for now.

**Closed by spacemeowx2** 2022-11-16 09:19 UTC
